[package]
name = "uwa-browser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
uwa-core.workspace = true
uwa-config = { path = "../uwa-config" }
uwa-stealth = { path = "../uwa-stealth" }
async-trait.workspace = true
tokio.workspace = true
dashmap.workspace = true
serde_json.workspace = true
tracing.workspace = true
url.workspace = true
futures.workspace = true
base64 = "0.21"
metrics = { version = "0.23", optional = true }
tokio-tungstenite = { version = "0.23", optional = true }
chromiumoxide = { version = "0.7.0", default-features = false, optional = true, features = [
    "tokio-runtime",
    "bytes",
] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
tracing.workspace = true
tracing-subscriber.workspace = true
libc = "0.2"

[features]
default = ["cdp"]
cdp = ["dep:chromiumoxide"]
nodriver = ["dep:tokio-tungstenite", "dep:metrics"]
metrics = ["dep:metrics"]
