[package]
name = "uwa-stealth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
uwa-core.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
async-trait.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
url.workspace = true
