[package]
name = "uwa-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
async-trait.workspace = true
url.workspace = true
uuid.workspace = true
tracing.workspace = true
tokio.workspace = true

[dev-dependencies]
serde_json.workspace = true
toml_edit = "0.22"
